# Generated by Django 4.2.3 on 2023-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_records_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
